version: "3.8"
services:
  postgres:
    image: postgres:10.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chintan@3540
      POSTGRES_DB: grocerydb

  api:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - postgres

volumes:
  pgdata:


# version: '3.8'

# services:
#   postgres:
#     image: postgres:10.4
#     container_name: postgres_container
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: Chintan@3540
#       POSTGRES_DB: grocerydb
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - pg_network

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin_container
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: admin123
#     ports:
#       - "5050:80"
#     depends_on:
#       - postgres
#     networks:
#       - pg_network

# volumes:
#   postgres_data:

# networks:
#   pg_network: